### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by mayuso** [mayuso/Datuk#17]
- [ ] Classify.
- [ ] Cluster.
- [x] Data.
- [x] Txt.
- [x] Excel. 
- [x] CommonFunctions.
- [x] Log.
- [ ] FXCharts:
  - [ ] FXLineChart (Still not developed, look at #20 ).
  - [ ] FXPieChart (Still not developed, look at #20 ).
  - [ ] FXBarChart (Still not developed, look at #20 ).

**Comment by mayuso** [comment]
Issue #23 regarding Excel class testing should be fixed before the next release.
